version: "3"

networks:
  app-network:
    driver: bridge

services:
  web:
    container_name: web
    build:
      context: ./services/web
      # `args` is used to make environment variables visible during the build. See https://docs.docker.com/compose/compose-file/compose-file-v3/#environment.
      args:
        - K_SERVER_URL=http://localhost:3002
        - E_SERVER_URL=http://localhost:5001
    ports:
      - 8080:80
    networks:
      - app-network

  graphql_server:
    container_name: graphql
    build: ./services/stats_server
    ports:
      - 4004:4004
    networks:
      - app-network

  controller_server:
    container_name: controller
    build: ./services/controller_server
    ports:
      - 3002:3002
    networks:
      - app-network
    environment:
      - K_SERVER_URL=http://localhost:3002
      - E_SERVER_URL=http://game:5001
      - G_SERVER_URL=http://graphql:4004/

  game_server:
    container_name: game
    build: ./services/game_server
    ports:
      - 5001:5001
    networks:
      - app-network
    environment:
      - K_SERVER_URL=http://localhost:3002
      - E_SERVER_URL=http://localhost:5001
      - G_SERVER_URL=http://localhost:4004/
